const images = [
    { id: 1, name: 'image_01', path: '/images/diploma/image_01.png' },
    { id: 2, name: 'image_02', path: '/images/diploma/image_02.png' },
    { id: 3, name: 'image_03', path: '/images/diploma/image_03.png' },
    { id: 4, name: 'image_04', path: '/images/diploma/Image_04.png' },
    { id: 5, name: 'image_05', path: '/images/diploma/Image_05.png' },
    { id: 6, name: 'image_06', path: '/images/diploma/Image_06.png' },
    { id: 7, name: 'image_07', path: '/images/diploma/Image_07.png' },
    { id: 8, name: 'image_08', path: '/images/diploma/Image_08.png' },
    { id: 9, name: 'image_09', path: '/images/diploma/Image_09.png' },
    { id: 10, name: 'image_10', path: '/images/diploma/Image_10.png' },
    { id: 11, name: 'image_11', path: '/images/diploma/Image_11.png' },
    { id: 12, name: 'image_12', path: '/images/diploma/Image_12.png' },
    { id: 13, name: 'image_13', path: '/images/diploma/Image_13.png' },
    { id: 14, name: 'image_14', path: '/images/diploma/Image_14.png' },
    { id: 15, name: 'image_15', path: '/images/diploma/Image_15.png' },
    { id: 16, name: 'image_16', path: '/images/diploma/Image_16.png' },
    { id: 17, name: 'image_17', path: '/images/diploma/Image_17.png' },
    { id: 18, name: 'image_18', path: '/images/diploma/Image_18.png' },
    { id: 19, name: 'image_19', path: '/images/diploma/Image_19.png' },
    { id: 20, name: 'image_20', path: '/images/diploma/Image_20.png' },
    { id: 21, name: 'image_21', path: '/images/diploma/Image_21.png' },
    { id: 22, name: 'image_22', path: '/images/diploma/Image_22.png' },
    { id: 23, name: 'image_23', path: '/images/diploma/Image_23.png' },
    { id: 24, name: 'image_24', path: '/images/diploma/Image_24.png' },
    { id: 25, name: 'image_25', path: '/images/diploma/Image_25.png' },
    { id: 26, name: 'image_26', path: '/images/diploma/Image_26.png' },
    { id: 27, name: 'image_27', path: '/images/diploma/Image_27.png' },
    { id: 28, name: 'image_28', path: '/images/diploma/Image_28.png' },
    { id: 29, name: 'image_29', path: '/images/diploma/Image_29.png' },
    { id: 30, name: 'image_30', path: '/images/diploma/Image_30.png' },
    { id: 31, name: 'image_31', path: '/images/diploma/Image_31.png' },
    { id: 32, name: 'image_32', path: '/images/diploma/Image_32.png' },
    { id: 33, name: 'image_33', path: '/images/diploma/Image_33.png' },
    { id: 34, name: 'image_34', path: '/images/diploma/Image_34.png' },
    { id: 35, name: 'image_35', path: '/images/diploma/Image_35.png' },
    { id: 36, name: 'image_36', path: '/images/diploma/Image_36.png' },
    { id: 37, name: 'image_37', path: '/images/diploma/Image_37.png' },
    { id: 38, name: 'image_38', path: '/images/diploma/Image_38.png' },
    { id: 39, name: 'image_39', path: '/images/diploma/Image_39.png' },
    { id: 40, name: 'image_40', path: '/images/diploma/Image_40.png' },
    { id: 41, name: 'image_41', path: '/images/diploma/Image_41.png' },
    { id: 42, name: 'image_42', path: '/images/diploma/Image_42.png' },
    { id: 43, name: 'image_43', path: '/images/diploma/Image_43.png' },
    { id: 44, name: 'image_44', path: '/images/diploma/Image_44.png' },
    { id: 45, name: 'image_45', path: '/images/diploma/Image_45.png' },
    { id: 46, name: 'image_46', path: '/images/diploma/Image_46.png' },
    { id: 47, name: 'image_47', path: '/images/diploma/Image_47.png' },
    { id: 48, name: 'image_48', path: '/images/diploma/Image_48.png' },
    { id: 49, name: 'image_49', path: '/images/diploma/Image_49.png' }
];

    
export default images